/**
 * HomeContent — homepage body converted 1:1 from public/index.html (Webflow export).
 * data-w-id attributes and IX2 inline initial styles are intentionally preserved;
 * HomeScripts re-initializes Webflow IX2 + loads GSAP/weblocks so animations run.
 * Generated by scripts/convert-home.py — edit with care.
 */
export default function HomeContent() {
  return (
    <>
      <section className="section-home-hero">
        <div className="hero_component">
          <div className="padding-global hero-padding-0">
            <div className="w-layout-blockcontainer container-large banner-container w-container">
              <div className="hero_wrapper">
                <div data-w-id="7b63f6bc-d323-fa22-a7d7-c59af79957f9" style={{ opacity: '0' }} className="hero_text-wrapper _1">
                  <h1 id="heading-h1" className="heading-style-h1 spacing-12 text-black w-inline-block">
                    <div className="text-block-53">Design. Think.</div>
                    <div className="text-block-54">Solve. Develop.</div>
                  </h1>
                  <p className="banner-subtitle">
                    Creating digital experiences that connect, engage and
                    <br />
                     inspire to help brands grow
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section_loop-text">
        <div className="loop_text-component">
          <div style={{ WebkitTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', MozTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', msTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', transform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)' }} className="loop_text-wrapper">
            <div className="loop_text">
              <div className="loop-service-text">Social Media Marketing</div>
              <div className="loop-service-text">Search engine Marketing</div>
              <div className="loop-service-text">BRANDING</div>
              <div className="loop-service-text">VIDEO Production</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">ui/UX</div>
            </div>
            <div className="loop_text">
              <div className="loop-service-text">Social Media Marketing</div>
              <div className="loop-service-text">Search engine Marketing</div>
              <div className="loop-service-text">BRANDING</div>
              <div className="loop-service-text">VIDEO Production</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">ui/UX</div>
            </div>
            <div className="loop_text">
              <div className="loop-service-text">Social Media Marketing</div>
              <div className="loop-service-text">Search engine Marketing</div>
              <div className="loop-service-text">BRANDING</div>
              <div className="loop-service-text">VIDEO Production</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">ui/UX</div>
            </div>
            <div className="loop_text">
              <div className="loop-service-text">Social Media Marketing</div>
              <div className="loop-service-text">Search engine Marketing</div>
              <div className="loop-service-text">BRANDING</div>
              <div className="loop-service-text">VIDEO Production</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">WEB & APP Development</div>
              <div className="loop-service-text">ui/UX</div>
            </div>
          </div>
        </div>
      </section>
      <section className="section-who-we-are">
        <div className="hero_header-component">
          <div className="padding-global">
            <div className="w-layout-blockcontainer container-large w-container">
              <div className="hero_header-wrapper">
                <img src="/images/who-we-are.png" loading="lazy" alt="Who we are — Marketing Mojito" className="header-image left-align" />
                <div className="hero_header-text left-align">
                  <div className="hero_header-left">
                    <h2 className="heading-style-h2">Who We Are </h2>
                  </div>
                  <div className="hero_header-right">
                    <div className="hero_header-para">
                      <p className="who-para left-align">Marketing Mojito is a full-service digital marketing agency in India, blending creativity with strategy to craft impactful digital experiences. We’re a team of designers, strategists, and marketers who believe in making brands stand out in a crowded digital world.</p>
                    </div>
                    <div className="hero_header-list left-align">
                      <a href="/about-us" className="button new-w-arrow w-button">About Us</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section-who-we-are seo-intro-section">
        <style
          dangerouslySetInnerHTML={{
            __html: `
.seo-intro-section .heading-style-h2 { white-space: normal; margin-bottom: 2rem; }
.seo-intro-cols { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem 4rem; align-items: start; }
.seo-intro-cta { margin-top: 1.5rem; }
@media (max-width: 767px) { .seo-intro-cols { grid-template-columns: 1fr; } }
`,
          }}
        />
        <div className="padding-global">
          <div className="w-layout-blockcontainer container-large w-container">
            <h2 className="heading-style-h2">Digital Marketing Services</h2>
            <div className="seo-intro-cols">
              <p className="who-para left-align">
                As a digital marketing company in India, we handle the full growth stack under one roof:{' '}
                <a href="/growth-marketing-seo-content-services">SEO and content marketing</a>,{' '}
                <a href="/paid-advertising">paid advertising and PPC</a>,{' '}
                <a href="/social-media-marketing">social media marketing</a>,{' '}
                <a href="/brand-visual-identity">branding and visual identity</a>,{' '}
                <a href="/motion-animation">motion graphics</a>,{' '}
                <a href="/photography-videography">video production</a>, and{' '}
                <a href="/websites-ecommerce">website and e-commerce development</a> — coordinated by one team,
                measured against one goal: qualified leads and revenue.
              </p>
              <div>
                <p className="who-para left-align">
                  We work with startups, D2C brands, SaaS companies, and established businesses across industries —
                  from <a href="/healthcare-marketing">healthcare</a> and{' '}
                  <a href="/real-estate-digital-marketing">real estate</a> to{' '}
                  <a href="/hospitality-digital-marketing">hospitality</a>,{' '}
                  <a href="/saas-digital-marketing">SaaS</a>, and{' '}
                  <a href="/entertainment-digital-marketing">entertainment</a>.
                </p>
                <div className="seo-intro-cta">
                  <a href="/contact-us" className="button new-w-arrow w-button">Book a Free Call</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section_loop-brands">
        <div className="loop_brand-component">
          <div className="loop_logs-wrapper">
            <div className="loop_band">
              <div className="brand_logo">
                <img loading="lazy" src="/images/1.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/2.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/3.png" alt="img" />
              </div>
              <div className="brand_logo _1">
                <img loading="lazy" src="/images/4.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/5.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/6.png" alt="img" />
              </div>
            </div>
            <div className="loop_band">
              <div className="brand_logo">
                <img loading="lazy" src="/images/7.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/8.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/9.png" alt="" />
              </div>
              <div className="brand_logo _1">
                <img loading="lazy" src="/images/10.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/11.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/12.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/13_1.png" alt="img" />
              </div>
            </div>
            <div className="loop_band">
              <div className="brand_logo">
                <img loading="lazy" src="/images/14.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/15.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/16.png" alt="img" />
              </div>
              <div className="brand_logo _1">
                <img loading="lazy" src="/images/17.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/18.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/19.png" alt="img" />
              </div>
            </div>
            <div className="loop_band">
              <div className="brand_logo">
                <img loading="lazy" src="/images/20.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/1.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/2.png" alt="img" />
              </div>
              <div className="brand_logo _1">
                <img loading="lazy" src="/images/3.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/4.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/5.png" alt="img" />
              </div>
            </div>
            <div className="loop_band">
              <div className="brand_logo">
                <img loading="lazy" src="/images/1.png" alt="" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/2.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/3.png" alt="img" />
              </div>
              <div className="brand_logo _1">
                <img loading="lazy" src="/images/4.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/5.png" alt="img" />
              </div>
              <div className="brand_logo">
                <img loading="lazy" src="/images/6.png" alt="img" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section_gallery-text">
        <div className="gallery_text-component">
          <div className="padding-global">
            <div className="w-layout-blockcontainer container-large w-container">
              <div className="galler-wrapper">
                <div className="gallery_text-wrapper right-align">
                  <div className="hero_header-left-2">
                    <h2 className="heading-style-h2">OUR SOLUTIONS</h2>
                  </div>
                  <div className="hero_header-right--2">
                    <div className="hero_header-para">
                      <p className="our-sol-para">We build websites, create memorable videos, and elevate your brand through media, SEO, and AEO. From strategy to storytelling, we craft digital experiences that stand out, engage, and drive growth.</p>
                    </div>
                    <div className="hero_header-list right-align">
                      <a href="https://marketingmojito.com/project/" target="_blank" className="button new-w-arrow our-solution w-button">Checkout Our Work</a>
                    </div>
                  </div>
                </div>
                <img src="/images/our-solution.png" loading="lazy" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 761px" srcSet="/images/our-solution-p-500.png 500w, /images/our-solution.png 761w" alt="Our solutions — Marketing Mojito" className="header-image right-align" />
              </div>
              <div className="code-embed-7 w-embed w-script">
                <style dangerouslySetInnerHTML={{ __html: `
    @import url('https://fonts.googleapis.com/css2?family=Unbounded:wght@400;500;700&display=swap');
  ` }} />
                <style dangerouslySetInnerHTML={{ __html: `
    /* ─── Base Reset ─── */
    .services-list, .services-list * {
      box-sizing: border-box;
      font-family: 'Unbounded', sans-serif;
      text-align: left;
    }
    .services-list {
      width: 100%;
      margin: 0;
      padding: 0;
    }
    .service-row:focus,
    .service-row a:focus {
      outline: none;
      -webkit-tap-highlight-color: transparent;
    }
    /* ─── Row Container ─── */
    .service-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px 16px;
      margin: 8px 0;
      background: #fff;
      border: 1px solid #ddd;
      border-radius: 6px;
      cursor: pointer;
      transition: transform .2s ease, background .2s ease, box-shadow .2s ease;
      height: 120px;
    }
    .service-row:hover,
    .service-row:focus {
      background: #f5f5f5;
      transform: translateY(-1px);
      box-shadow: 0 2px 4px rgba(0,0,0,0.08);
    }
    /* ─── Left Side (Icon + Title) ─── */
    .service-row .left {
      display: flex;
      align-items: center;
      flex: 0 0 35%;
      min-width: 150px;
    }
    .service-row .left .icon {
      width: 24px;
      height: 24px;
      margin-right: 8px;
      opacity: 0.6;
    }
    .service-row .left .icon img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
    .service-row .left .title {
      font-size: 1.563rem;
      font-weight: 500;
      color: #333;
    }
    /* ─── Right Side (Two Flex Columns) ─── */
    .service-row .right-list {
      display: flex;
      flex: 0 0 55%;
      justify-content: space-between;
      gap: 24px;
      padding-left: 20px;
    }
    .service-row .right-list .service-column {
      display: flex;
      flex-direction: column;
      gap: 4px;
      flex: 1;
    }
    .service-row .right-list .service-column a {
      display: inline-block;
      padding: 2px 6px;
      background: #e6f4e6;
      color: #333;
      border: 1px solid transparent;
      border-radius: 3px;
      text-decoration: none;
      font-weight: 500;
      white-space: nowrap;
      transition: background .2s, color .2s, border-color .2s;
      text-align: left;
    }
    .service-row .right-list .service-column a:hover,
    .service-row .right-list .service-column a:focus {
      background: #82C341;
      color: #fff;
      border-color: #82C341;
    }
    /* ─── Hover-preview ─── */
    #hover-preview {
      position: absolute;
      pointer-events: none;
      width: 150px;
      max-width: 20vw;
      opacity: 0;
      transform: scale(0.7); /* no centering translate */
      transition: opacity .2s ease, transform .2s ease;
      border-radius: 6px;
      overflow: hidden;
      box-shadow: 0 6px 16px rgba(0,0,0,0.15);
      z-index: 999;
      left: 0;  /* default so first move places it deterministically */
      top: 0;
    }
    #hover-preview img {
      display: block;
      width: 100%;
      height: auto;
      opacity: 0.8;
    }
    /* ─── Mobile ─── */
    @media (max-width: 768px) {
      .service-row {
        flex-direction: column;
        align-items: center;
        height: auto;
        padding: 12px 8px;
        text-align: center;
      }
      .service-row .left {
        flex: 1 1 100%;
        min-width: auto;
        margin-bottom: 12px;
        justify-content: center;
        text-align: center;
      }
      .service-row .left .icon {
        width: 20px;
        height: 20px;
        margin-right: 6px;
      }
      .service-row .left .title {
        font-size: 1.1rem;
        text-align: center;
      }
      .service-row .right-list {
        flex: 1 1 100%;
        flex-direction: column;
        gap: 8px;
        width: 100%;
        padding-left: 0;
        align-items: center;
      }
      .service-row .right-list .service-column {
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: center;
        gap: 6px;
        width: 100%;
      }
      .service-row .right-list .service-column a {
        font-size: 0.8rem;
        padding: 4px 8px;
        text-align: center;
        white-space: nowrap;
      }
      /* Hide hover preview on mobile */
      #hover-preview {
        display: none;
      }
    }
  ` }} />
                <div className="services-list">
                  <div className="service-row" tabIndex={0} data-img="https://cdn.prod.website-files.com/6821a11a1adb296fa1dad4b9/6877998c379b303b1d289276_digital%20transformation%20(1)%20(1)-p-2600.png">
                    <div className="left">
                      <div className="icon">
                        <img src="https://unpkg.com/ionicons@5.5.2/dist/svg/cloud-download-outline.svg" alt="" />
                      </div>
                      <div className="title">Digital Transformation</div>
                    </div>
                    <div className="right-list">
                      <div className="service-column">
                        <a href="https://marketingmojito.com/websites-ecommerce">Websites & E-Commerce</a>
                      </div>
                      <div className="service-column">
                        <a href="https://marketingmojito.com/ai-powered-automation">AI-Powered Automation</a>
                      </div>
                    </div>
                  </div>
                  <div className="service-row" tabIndex={0} data-img="https://cdn.prod.website-files.com/6821a11a1adb296fa1dad4b9/685d2b80d5b8aaa22985bafd_Branding.png">
                    <div className="left">
                      <div className="icon">
                        <img src="https://unpkg.com/ionicons@5.5.2/dist/svg/brush-outline.svg" alt="" />
                      </div>
                      <div className="title">Brand & Visual Identity</div>
                    </div>
                    <div className="right-list">
                      <div className="service-column">
                        <a href="https://marketingmojito.com/brand-visual-identity">Brand & Visual ID</a>
                        <a href="https://marketingmojito.com/motion-animation">Motion & Animation</a>
                      </div>
                      <div className="service-column">
                        <a href="https://marketingmojito.com/photography-videography">Photography & Videography</a>
                      </div>
                    </div>
                  </div>
                  <div className="service-row" tabIndex={0} data-img="https://cdn.prod.website-files.com/6821a11a1adb296fa1dad4b9/685d2b8016d23f6af671fcc7_performance%20analytics.png">
                    <div className="left">
                      <div className="icon">
                        <img src="https://unpkg.com/ionicons@5.5.2/dist/svg/trending-up-outline.svg" alt="" />
                      </div>
                      <div className="title">Growth Marketing</div>
                    </div>
                    <div className="right-list">
                      <div className="service-column">
                        <a href="https://marketingmojito.com/paid-advertising">Paid Advertising</a>
                        <a href="https://marketingmojito.com/growth-marketing-seo-content-services">Growth & SEO Content</a>
                      </div>
                      <div className="service-column">
                        <a href="https://marketingmojito.com/performance-analytics-cro-services">Analytics & CRO</a>
                      </div>
                    </div>
                  </div>
                  <div className="service-row" tabIndex={0} data-img="/images/68568017e3cef5056aaffac0_Social-Media-Engagement-1.png">
                    <div className="left">
                      <div className="icon">
                        <img src="https://unpkg.com/ionicons@5.5.2/dist/svg/chatbubbles-outline.svg" alt="" />
                      </div>
                      <div className="title">Social Media Marketing</div>
                    </div>
                    <div className="right-list">
                      <div className="service-column">
                        <a href="https://marketingmojito.com/strategy-management">Strategy & Management</a>
                        <a href="https://marketingmojito.com/personal-branding">Personal Branding</a>
                      </div>
                      <div className="service-column">
                        <a href="https://marketingmojito.com/viral-content-shorts-page">Viral Content & Shorts</a>
                      </div>
                    </div>
                  </div>
                  <div className="service-row" tabIndex={0} data-img="https://cdn.prod.website-files.com/6821a11a1adb296fa1dad4b9/685d2b83eceb06b732495971_SEO.png">
                    <div className="left">
                      <div className="icon">
                        <img src="https://unpkg.com/ionicons@5.5.2/dist/svg/business-outline.svg" alt="" />
                      </div>
                      <div className="title">Industries We Serve</div>
                    </div>
                    <div className="right-list">
                      <div className="service-column">
                        <a href="https://marketingmojito.com/e-commerce-digital-marketing">E-Commerce</a>
                        <a href="https://marketingmojito.com/healthcare-marketing">Healthcare</a>
                        <a href="https://marketingmojito.com/real-estate-digital-marketing">Real Estate</a>
                      </div>
                      <div className="service-column">
                        <a href="https://marketingmojito.com/saas-digital-marketing">SaaS</a>
                        <a href="https://marketingmojito.com/hospitality-digital-marketing">Hospitality</a>
                        <a href="https://marketingmojito.com/entertainment-digital-marketing">Entertainment</a>
                      </div>
                    </div>
                  </div>
                </div>
                <div id="hover-preview">
                  <img src="" alt="" />
                </div>
              </div>
              <div className="new-box-wrapper">
                <div data-w-id="bbdbd0f3-0b73-6944-f151-085be90a0e92" className="new-box">
                  <img src="/images/cloud-download-outline.svg" loading="lazy" width="Auto" style={{ width: '50px', height: '52px' }} alt="" className="web-box-icons" />
                  <div className="content-box-wrapper">
                    <div className="box-title-wrapper">
                      <h4 className="heading-12">Digital Transformation</h4>
                      <img src="/images/icon-2.png" loading="lazy" style={{ WebkitTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', MozTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', msTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transformStyle: 'preserve-3d' }} alt="" className="arrow-icon" />
                    </div>
                    <div className="content-box add-left-space flex-box">
                      <a href="/websites-ecommerce" className="page-name">Website & E-Commerce</a>
                      <a href="/ai-powered-automation" className="page-name">AI-Powered Automation</a>
                    </div>
                  </div>
                </div>
                <div data-w-id="bbdbd0f3-0b73-6944-f151-085be90a0e9c" className="new-box">
                  <img src="/images/brush-outline.svg" loading="lazy" width="Auto" style={{ width: '50px', height: '52px' }} alt="" className="web-box-icons" />
                  <div className="content-box-wrapper">
                    <div className="box-title-wrapper">
                      <h4 className="heading-12">Brand & Visual identity</h4>
                      <img src="/images/icon-2.png" loading="lazy" style={{ WebkitTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', MozTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', msTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transformStyle: 'preserve-3d' }} alt="" className="arrow-icon" />
                    </div>
                    <div className="content-box add-left-space flex-box">
                      <a href="/brand-visual-identity" className="page-name">Brand And Visual ID</a>
                      <a href="/photography-videography" className="page-name">Photography & Videography</a>
                      <a href="/motion-animation" className="page-name">Motion & Animation</a>
                    </div>
                  </div>
                </div>
                <div data-w-id="bbdbd0f3-0b73-6944-f151-085be90a0ea6" className="new-box">
                  <img src="/images/trending-up-outline.svg" loading="lazy" width="Auto" style={{ width: '50px', height: '52px' }} alt="" className="web-box-icons" />
                  <div className="content-box-wrapper">
                    <div className="box-title-wrapper">
                      <h4 className="heading-12">Growth Marketing</h4>
                      <img src="/images/icon-2.png" loading="lazy" style={{ WebkitTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', MozTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', msTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transformStyle: 'preserve-3d' }} alt="" className="arrow-icon" />
                    </div>
                    <div className="content-box add-left-space flex-box">
                      <a href="/paid-advertising" className="page-name">Paid Advertising</a>
                      <a href="/performance-analytics-cro-services" className="page-name">Analytics & CRO</a>
                      <a href="/growth-marketing-seo-content-services" className="page-name">Growth & SEO Content</a>
                    </div>
                  </div>
                </div>
                <div data-w-id="bbdbd0f3-0b73-6944-f151-085be90a0eb0" className="new-box">
                  <img src="/images/chatbubbles-outline.svg" loading="lazy" width="Auto" style={{ width: '50px', height: '52px' }} alt="" className="web-box-icons" />
                  <div className="content-box-wrapper">
                    <div className="box-title-wrapper">
                      <h4 className="heading-12">Social Media Marketing</h4>
                      <img src="/images/icon-2.png" loading="lazy" style={{ WebkitTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', MozTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', msTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transformStyle: 'preserve-3d' }} alt="" className="arrow-icon" />
                    </div>
                    <div className="content-box add-left-space flex-box">
                      <a href="/strategy-management" className="page-name">Strategy Management</a>
                      <a href="/personal-branding" className="page-name">Personal Branding</a>
                      <a href="/viral-content-shorts-page" className="page-name">Viral Content & Shorts</a>
                    </div>
                  </div>
                </div>
                <div data-w-id="9dba60d4-d363-2132-61f9-febd6cdb5266" className="new-box">
                  <img src="/images/business-outline.png" loading="lazy" width="Auto" style={{ width: '50px', height: '52px' }} alt="" className="web-box-icons" />
                  <div className="content-box-wrapper">
                    <div className="box-title-wrapper">
                      <h4 className="heading-12">Industries We Serve</h4>
                      <img src="/images/icon-2.png" loading="lazy" style={{ WebkitTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', MozTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', msTransform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transform: 'translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0deg) skew(0, 0)', transformStyle: 'preserve-3d' }} alt="" className="arrow-icon" />
                    </div>
                    <div className="content-box add-left-space flex-box">
                      <a href="/e-commerce-digital-marketing" className="page-name">E-Commerce</a>
                      <a href="/healthcare-marketing" className="page-name">Healthcare</a>
                      <a href="/real-estate-digital-marketing" className="page-name">Real Estate</a>
                      <a href="/saas-digital-marketing" className="page-name">SaaS</a>
                      <a href="/hospitality-digital-marketing" className="page-name">Hospitality</a>
                      <a href="/entertainment-digital-marketing" className="page-name">Entertainment</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="feedback">
        <div className="padding-global">
          <div className="container-large">
            <div className="portfolio-card-wrapper">
              <div className="div-block-97">
                <div className="cards_text-wrapper left-align portfolio-title">
                  <div data-w-id="8586f135-91c8-79c7-f248-31ec5b72f08d" style={{ opacity: '0' }} className="cards_text-left">
                    <h2 className="heading-style-h2">PORTFOLIO</h2>
                  </div>
                  <div data-w-id="8586f135-91c8-79c7-f248-31ec5b72f090" style={{ opacity: '0' }} className="cards_text-right left-align">
                    <div className="cards_text-para">
                      <p className="text-48 left-align">You name it, we’ve built it.       </p>
                    </div>
                  </div>
                </div>
                <div className="mob-arrow-wrap">
                  <img src="/images/gg_arrow-up-o.png" loading="lazy" alt="" className="image-44" />
                </div>
              </div>
              <div className="startup-desgin-wrapper">
                <div data-w-id="a2c79637-c3d3-8e53-a987-b59ee824f827" className="startup_brand-block-2">
                  <img loading="lazy" src="/images/29.png" alt="" className="image-43" />
                  <div className="brand_text-wrapper">
                    <div className="portfolio-cards-title">Branding Agencies 101: Everything You Need to Know</div>
                    <div className="portfolio-para">Branding Agencies 101” is your complete guide to understanding what branding agencies do, their services, and how they help businesses create strong visual and emotional connections with customers. Learn key insights to choose the right agency for your brand journey.</div>
                  </div>
                  <div className="option-brand">
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Logo Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Web Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Print</div>
                    </div>
                  </div>
                  <div className="startup-mask-2">
                    <a href="https://marketingmojito.com/blog/what-does-a-branding-agency-do/" className="project-btn w-button">Project link</a>
                  </div>
                </div>
                <div data-w-id="a2c79637-c3d3-8e53-a987-b59ee824f83b" className="startup_brand-block-2">
                  <img loading="lazy" src="/images/13.png" alt="" className="image-43" />
                  <div className="brand_text-wrapper">
                    <div className="portfolio-cards-title">Crack the Code: Lead Generation for Real Estate in India</div>
                    <div className="portfolio-para">Unlock the secrets to effective lead generation in India’s dynamic real estate market. Discover proven strategies, digital tools, and marketing techniques that help realtors attract quality leads and close more deals.</div>
                  </div>
                  <div className="option-brand">
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Logo Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Web Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Print</div>
                    </div>
                  </div>
                  <div className="startup-mask-2">
                    <a href="https://marketingmojito.com/blog/generate-leads-for-real-estate-business-of-india/" className="project-btn w-button">Project link</a>
                  </div>
                </div>
                <div data-w-id="a2c79637-c3d3-8e53-a987-b59ee824f84f" className="startup_brand-block-2">
                  <img loading="lazy" src="/images/43.png" alt="" className="image-43" />
                  <div className="brand_text-wrapper">
                    <div className="portfolio-cards-title">How To Build A Memorable Company Presence On LinkedIn</div>
                    <div className="portfolio-para">Want your brand to shine on LinkedIn? Explore practical tips to build a memorable company presence that attracts followers, boosts engagement, and strengthens your business credibility.</div>
                  </div>
                  <div className="option-brand">
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Logo Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Web Design</div>
                    </div>
                    <div className="brand-option">
                      <div className="text-14 text-weight-semibold whitr">Print</div>
                    </div>
                  </div>
                  <div className="startup-mask-2">
                    <a href="https://marketingmojito.com/blog/how-to-make-your-company-stand-out-on-linkedin/" className="project-btn w-button">Project link</a>
                  </div>
                </div>
                <div className="code-embed-8 w-embed">
                  <style dangerouslySetInnerHTML={{ __html: `
    .portfolio-para {
        overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        line-clamp: 3;
        -webkit-box-orient: vertical;
    }
    .portfolio-cards-title{
       overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        line-clamp: 1;
        -webkit-box-orient: vertical;
    }
    ` }} />
                </div>
              </div>
            </div>
            <div className="div-block-85">
              <a href="/portfolio" className="button new-w-arrow see-all-project w-button">See all Projects</a>
            </div>
          </div>
        </div>
      </section>
      <section className="section_testimonials">
        <div className="testimonial_text-component">
          <div className="padding-global">
            <div className="w-layout-blockcontainer container-large w-container">
              <div className="div-block-3">
                <div className="testimonial_text-wrapper">
                  <div data-w-id="7b63f6bc-d323-fa22-a7d7-c59af7995988" style={{ opacity: '0' }} className="testimonial_text-left">
                    <h2 className="heading-style-h2">CLIENT SUCCESS</h2>
                  </div>
                  <div data-w-id="7b63f6bc-d323-fa22-a7d7-c59af799598b" style={{ opacity: '0' }} className="testimonial_text-right _1">
                    <div className="cards_text-para">
                      <p className="text-48">Hear from our happy customers!</p>
                    </div>
                  </div>
                </div>
                <div className="testimonial">
                  <div className="client-box">
                    <div className="client-box">
                      <div className="client-card">
                        <div className="client-des">“Working with Marketing Mojito felt like adding a growth engine to our team. From revamping our brand identity to driving real results on LinkedIn, they’ve been instrumental in our B2B strategy. Truly a partner, not just a vendor.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-18.png" alt="" />
                            <div>
                              <div className="text-block-8">Deepak</div>
                              <div className="text-block-9">Founder – AeonX</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Marketing Mojito has redefined how we present Indian culture to the world. Their content curation and influencer strategies are absolutely on point – engaging, vibrant, and always trending.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/karamjeetdua.png" alt="" />
                            <div>
                              <div className="text-block-8">Karamjeet Dua</div>
                              <div className="text-block-9">Founder – XploreIndia Stream</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Their data-backed digital strategies aligned seamlessly with our vision. It’s rare to find a creative team that understands performance metrics and AI trends as well as they do.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-19.png" alt="" />
                            <div>
                              <div className="text-block-8">Dr. Biswajit</div>
                              <div className="text-block-9">Design Team Lead at VMware</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“In the hospitality space, standing out is tough. Marketing Mojito made it look easy. From stunning visuals to compelling storytelling – they brought our properties to life online.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/sa.png" alt="" />
                            <div>
                              <div className="text-block-8">Saurabh Gahoi</div>
                              <div className="text-block-9">SVP Marketing – Ramee Group</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“What I admire most is their ability to blend creativity with corporate clarity. Their LinkedIn campaigns boosted our employer brand and recruitment efforts beyond expectations.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-18.png" alt="" />
                            <div>
                              <div className="text-block-8">Sunil Sathe</div>
                              <div className="text-block-9">Corporate Communication Head – Ashapura Group</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“They understood our brand&apos;s tone and internal alignment needs with impressive precision. Seamless execution, fast turnaround, and consistently impactful content.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/female-icon.png" alt="" />
                            <div>
                              <div className="text-block-8">Yashika</div>
                              <div className="text-block-9">Corporate Communications – JWIL</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Marketing Mojito beautifully translated my music and legacy into the digital space. Their social media management and event promotions helped us connect with a whole new generation.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/hariharan-ji.png" alt="" />
                            <div>
                              <div className="text-block-8">Hariharan</div>
                              <div className="text-block-9">Singer & Padma Shri Awardee</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“They captured the essence of my art and heritage with grace. I now have a digital presence that truly resonates with my audience and elevates my brand.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/jaspinder-narula.png" alt="" />
                            <div>
                              <div className="text-block-8">Jaspinder Narula</div>
                              <div className="text-block-9">Singer & Padma Shri Awardee</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Entertainment marketing needs a pulse on what’s hot – and Marketing Mojito has that instinct. From buzz-worthy content to strategic collaborations, they deliver every time.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-19.png" alt="" />
                            <div>
                              <div className="text-block-8">Vishal G</div>
                              <div className="text-block-9">Founder – Morya Entertainment</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Working with Marketing Mojito felt like adding a growth engine to our team. From revamping our brand identity to driving real results on LinkedIn, they’ve been instrumental in our B2B strategy. Truly a partner, not just a vendor.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-18.png" alt="" />
                            <div>
                              <div className="text-block-8">Deepak</div>
                              <div className="text-block-9">Founder – AeonX</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Marketing Mojito has redefined how we present Indian culture to the world. Their content curation and influencer strategies are absolutely on point – engaging, vibrant, and always trending.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/karamjeetdua.png" alt="" />
                            <div>
                              <div className="text-block-8">Karamjeet Dua</div>
                              <div className="text-block-9">Founder – XploreIndia Stream</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                      <div className="client-card">
                        <div className="client-des">“Their data-backed digital strategies aligned seamlessly with our vision. It’s rare to find a creative team that understands performance metrics and AI trends as well as they do.”</div>
                        <div className="client_detils">
                          <div className="client-name">
                            <img loading="lazy" src="/images/New-Project-19.png" alt="" />
                            <div>
                              <div className="text-block-8">Dr. Biswajit</div>
                              <div className="text-block-9">Design Team Lead at VMware</div>
                            </div>
                          </div>
                          <div>
                            <img loading="lazy" src="/images/icon-quotes.svg" alt="" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section_loop-intro">
        <div className="loop_intro-component">
          <div className="loop_into-wrapper">
            <div style={{ WebkitTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', MozTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', msTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', transform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)' }} className="loop_intro left">
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
            </div>
            <div style={{ WebkitTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', MozTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', msTransform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)', transform: 'translate3d(0vw, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)' }} className="loop_intro right">
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
              <div className="into_text">
                <div className="text-36">LET’S Work Together</div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="padding-global">
        <div className="w-layout-blockcontainer container-large w-container">
          <div className="contacr-wrapperr">
            <div className="contact_text-wrapper">
              <div className="cta-heading-wrapper">
                <h3 className="heading-style-h3 white">Is Your Marketing Working?</h3>
                <h3 className="heading-style-h3 yellow">Get a Free Self-Audit Checklist Now!</h3>
              </div>
              <div className="contact_form-wrapper">
                <div className="w-embed w-script">
                  <style dangerouslySetInnerHTML={{ __html: `
.custom-form-wrapper {
  max-width: 430px;
  margin: 0 auto;
  padding: 15px;
  background: linear-gradient(135deg, #FDB913 0%, #F5A623 100%);
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
}
.custom-form-wrapper input[type="text"],
.custom-form-wrapper input[type="email"] {
  width: 100%;
  padding: 12px 20px;
  margin-bottom: 8px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-family: inherit;
  background: #FFFFFF;
  color: #333;
  box-sizing: border-box;
  transition: all 0.3s ease;
  text-align: center;
}
.custom-form-wrapper input::placeholder {
  color: #B8B8B8;
  font-weight: 400;
  text-align: center;
}
.custom-form-wrapper input:focus {
  outline: none;
  box-shadow: 0 0 0 2px rgba(255, 255, 255, 0.3);
}
.custom-form-wrapper button[type="submit"] {
  width: 100%;
  padding: 12px 20px;
  margin-top: 4px;
  background: transparent;
  border: none;
  color: #FFFFFF;
  font-size: 18px;
  font-weight: 600;
  cursor: pointer;
  border-radius: 6px;
  transition: all 0.3s ease;
  font-family: inherit;
  text-align: center;
}
.custom-form-wrapper button[type="submit"]:hover {
  background: rgba(255, 255, 255, 0.1);
  transform: translateY(-1px);
}
.custom-form-wrapper button[type="submit"]:active {
  transform: translateY(0);
}
.custom-form-wrapper button[type="submit"]:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}
.hidden {
  display: none !important;
}
.success-message {
  padding: 20px;
  background: #4CAF50;
  color: white;
  border-radius: 8px;
  text-align: center;
  font-size: 16px;
  font-weight: 500;
}
` }} />
                  <div className="custom-form-wrapper">
                    <form action="#" method="POST" id="checklist-form" data-pdf-name="Self-Audit Checklist" data-page-name="Home">
                      <input type="checkbox" name="botcheck" className="hidden" />
                      <input type="text" name="name" placeholder="Name" required />
                      <input type="email" name="email" placeholder="Your e-mail Address" required />
                      <button type="submit">Get the Checklist</button>
                    </form>
                  </div>
                </div>
              </div>
              <div className="cta-mail-infor-wrapper">
                <p className="text-18 cta-info-para">If it isn&apos;t then reach out to us at </p>
                <p className="paragraph-4">hello@marketingmojito.com</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="whatsapp-block">
        <a id="whatsapp-button" data-w-id="56d04114-1b9f-fba3-03d9-bfa1040cf8fd" href="https://api.whatsapp.com/send?phone=919152605355" className="whatsapp-container w-inline-block">
          <img loading="lazy" src="/images/whatsapp.svg" alt="" className="whatsapp-icon" />
        </a>
      </div>
      {/* Mobile line-clamp removed: it hid the SEO copy and its internal links on phones. */}
    </>
  );
}
